import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

const SERVICES=[['oil-change','Oil Change'],['transmission','Transmission'],['tyre-change','Tyre Change'],['flat-fix','Flat Fix'],['brake-service','Brake Service'],['air-conditioning','Air Conditioning'],['sensors','Sensors'],['programming','Programming'],['diagnostics','Diagnostics'],['battery','Battery'],['wash-detail','Wash & Detail'],['towing','Towing'],['other','Other']]
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const dateLabel=d=>d?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${d}T12:00:00`)):'—'
const timeLabel=t=>String(t||'').slice(0,5)||'—'
const statusClass=s=>['paid','completed','approved','confirmed','scheduled','succeeded'].includes(String(s||'').toLowerCase())?'good':String(s||'').toLowerCase()==='cancelled'?'bad':''

export default function Dashboard({session}){
  const [role,setRole]=useState('checking'); const [tab,setTab]=useState('overview'); const [busy,setBusy]=useState(true); const [error,setError]=useState('')
  const [bookings,setBookings]=useState([]); const [payments,setPayments]=useState([]); const [applications,setApplications]=useState([]); const [tech,setTech]=useState(null); const [availability,setAvailability]=useState([]); const [timeOff,setTimeOff]=useState([])
  const [profile,setProfile]=useState({name:'',phone:'',services:[],base_address:'',base_lat:'',base_lng:'',available_for_jobs:true,active:true,avatar_url:''})
  const [appFilter,setAppFilter]=useState('pending'); const [locationOn,setLocationOn]=useState(false); const [locationMsg,setLocationMsg]=useState('')

  const load=useCallback(async()=>{
    setBusy(true);setError('')
    const {data:{user}}=await supabase.auth.getUser(); if(!user){setRole('none');setBusy(false);return}
    const admin=await supabase.from('admin_users').select('user_id,active').eq('user_id',user.id).eq('active',true).maybeSingle()
    const technician=await supabase.from('technicians').select('*').eq('user_id',user.id).maybeSingle()
    if(admin.error||technician.error){setError(admin.error?.message||technician.error?.message||'Could not identify this account.');setBusy(false);return}
    setRole(admin.data?'admin':technician.data?'technician':'none')
    if(!admin.data&&!technician.data){setError('This account is not an active Viso administrator or technician.');setBusy(false);return}
    const assigned=technician.data&&!admin.data?`&assigned_technician_id=eq.${technician.data.id}`:''
    const [b,p,a,av,off]=await Promise.all([
      supabase.from('bookings').select('*').order('appointment_date',{ascending:true}).order('appointment_time',{ascending:true}),
      supabase.from('payments').select('*').order('created_at',{ascending:false}),
      admin.data?supabase.from('technician_applications').select('*').order('created_at',{ascending:false}):Promise.resolve({data:[],error:null}),
      technician.data?supabase.from('technician_availability').select('*').eq('technician_id',technician.data.id).order('weekday').order('start_time'):Promise.resolve({data:[],error:null}),
      technician.data?supabase.from('technician_time_off').select('*').eq('technician_id',technician.data.id).order('date'):Promise.resolve({data:[],error:null}),
    ])
    if(b.error||p.error||a.error||av.error||off.error){setError(b.error?.message||p.error?.message||a.error?.message||av.error?.message||off.error?.message||'Could not load data.');}
    let nextBookings=b.data||[]; if(technician.data&&!admin.data) nextBookings=nextBookings.filter(x=>x.assigned_technician_id===technician.data.id)
    let nextPayments=p.data||[]; if(technician.data&&!admin.data){const ids=new Set(nextBookings.map(x=>x.id));nextPayments=nextPayments.filter(x=>ids.has(x.booking_id))}
    setBookings(nextBookings);setPayments(nextPayments);setApplications(a.data||[]);setTech(technician.data||null);setAvailability(av.data||[]);setTimeOff(off.data||[])
    if(technician.data)setProfile({name:technician.data.name||'',phone:technician.data.phone||'',services:Array.isArray(technician.data.services)?technician.data.services:[],base_address:technician.data.base_address||'',base_lat:technician.data.base_lat??'',base_lng:technician.data.base_lng??'',available_for_jobs:technician.data.available_for_jobs!==false,active:technician.data.active!==false,avatar_url:technician.data.avatar_url||''})
    setBusy(false)
  },[])
  useEffect(()=>{load();const ch=supabase.channel('viso-ops').on('postgres_changes',{event:'*',schema:'public',table:'bookings'},load).on('postgres_changes',{event:'*',schema:'public',table:'payments'},load).on('postgres_changes',{event:'*',schema:'public',table:'technician_applications'},load).subscribe();return()=>supabase.removeChannel(ch)},[load])

  const stats=useMemo(()=>{const today=new Date().toISOString().slice(0,10);const paid=payments.filter(p=>['paid','succeeded','completed','success'].includes(String(p.status||'').toLowerCase())).reduce((s,p)=>s+Number(p.amount||0),0);return{revenue:paid,today:bookings.filter(b=>b.appointment_date===today).length,upcoming:bookings.filter(b=>b.appointment_date>=today&&!['cancelled','completed'].includes(String(b.status||'').toLowerCase())).length,pending:bookings.filter(b=>['pending','confirmed','scheduled'].includes(String(b.status||'').toLowerCase())).length}} , [bookings,payments])
  async function signOut(){await supabase.auth.signOut()}
  async function updateBooking(id,status){const {error}=await supabase.from('bookings').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)setError(error.message);else load()}
  async function saveProfile(){if(!tech)return;setError('');const {error}=await supabase.from('technicians').update({...profile,base_lat:profile.base_lat===''?null:Number(profile.base_lat),base_lng:profile.base_lng===''?null:Number(profile.base_lng),updated_at:new Date().toISOString()}).eq('id',tech.id);if(error)setError(error.message);else load()}
  async function toggleService(id){setProfile(p=>({...p,services:p.services.includes(id)?p.services.filter(x=>x!==id):[...p.services,id]}))}
  async function saveAvailability(row){const payload={technician_id:tech.id,weekday:Number(row.weekday),start_time:row.start_time,end_time:row.end_time,active:row.active!==false};const q=String(row.id).startsWith('new-')?supabase.from('technician_availability').insert(payload):supabase.from('technician_availability').update(payload).eq('id',row.id);const {error}=await q;if(error)setError(error.message);else load()}
  async function deleteAvailability(id){const {error}=await supabase.from('technician_availability').delete().eq('id',id);if(error)setError(error.message);else load()}
  async function addTimeOff(e){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('technician_time_off').insert({technician_id:tech.id,date:f.get('date'),reason:f.get('reason')||null});if(error)setError(error.message);else{e.currentTarget.reset();load()}}
  async function removeTimeOff(id){const {error}=await supabase.from('technician_time_off').delete().eq('id',id);if(error)setError(error.message);else load()}
  async function uploadAvatar(file){
    if(!tech||!file)return;
    if(!file.type.startsWith('image/')){setError('Choose an image file.');return}
    if(file.size>5*1024*1024){setError('Profile images must be 5MB or smaller.');return}
    const ext=(file.name.split('.').pop()||'jpg').toLowerCase();
    const path=`${tech.user_id}/${Date.now()}.${ext}`;
    const {error:uploadError}=await supabase.storage.from('profile-photos').upload(path,file,{upsert:true,contentType:file.type});
    if(uploadError){setError(uploadError.message);return}
    const {data}=supabase.storage.from('profile-photos').getPublicUrl(path);
    const {error:updateError}=await supabase.from('technicians').update({avatar_url:data.publicUrl,updated_at:new Date().toISOString()}).eq('id',tech.id);
    if(updateError)setError(updateError.message);else load();
  }
  async function locationPing(){setLocationMsg('Requesting location…');if(!navigator.geolocation){setLocationMsg('This device does not provide browser location.');return}navigator.geolocation.getCurrentPosition(async pos=>{const {latitude,longitude,accuracy}=pos.coords;const {data:{session:current}}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ping-technician-location`,{method:'POST',headers:{'Content-Type':'application/json',apikey:import.meta.env.VITE_SUPABASE_ANON_KEY,Authorization:`Bearer ${current.access_token}`},body:JSON.stringify({latitude,longitude,accuracyMeters:accuracy})});const result=await r.json().catch(()=>({}));setLocationMsg(r.ok?'Location shared.':'Location error: '+(result.error||'unknown'));},()=>setLocationMsg('Location permission was denied.'),{enableHighAccuracy:true,maximumAge:30000,timeout:10000})}
  useEffect(()=>{if(!locationOn||!tech)return;locationPing();const id=setInterval(locationPing,60000);return()=>clearInterval(id)},[locationOn,tech?.id])
  async function applicationAction(id,action){setError('');const {data:{session:current}}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/admin-technician-action`,{method:'POST',headers:{'Content-Type':'application/json',apikey:import.meta.env.VITE_SUPABASE_ANON_KEY,Authorization:`Bearer ${current.access_token}`},body:JSON.stringify({action,applicationId:id})});const result=await r.json().catch(()=>({}));if(!r.ok)setError(result.error||'Action failed');else load()}
  async function connect(action){const {data:{session:current}}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/stripe-connect`,{method:'POST',headers:{'Content-Type':'application/json',apikey:import.meta.env.VITE_SUPABASE_ANON_KEY,Authorization:`Bearer ${current.access_token}`},body:JSON.stringify({action,technicianId:tech.id,returnUrl:window.location.origin,cancelUrl:window.location.origin})});const result=await r.json().catch(()=>({}));if(!r.ok)setError(result.error||'Stripe Connect action failed');else if(result.url)window.location.assign(result.url)}
  if(role==='checking')return <div className="screen-center"><div className="brand-mark">VISO</div><span>Loading operations…</span></div>
  if(role==='none')return <div className="screen-center"><div><div className="brand-mark">VISO</div><p className="error">{error||'No Viso access is attached to this account.'}</p><button className="primary" onClick={signOut}>Sign out</button></div></div>

  const isAdmin=role==='admin'
  const tabs=isAdmin?['overview','bookings','applications','technician','availability','payments']:['overview','bookings','availability','payments']
  return <main className="app-shell">
    <header className="topbar"><div className="brand-lockup"><span className="brand-mark">VISO</span><span>Mobile Autocare · {isAdmin?'Operations':'Technician'}</span></div><div className="top-actions"><span className="account-email">{session.user.email}</span><button className="ghost" onClick={load}>Refresh</button><button className="ghost" onClick={signOut}>Sign out</button></div></header>
    <div className="layout"><aside className="sidebar"><p className="eyebrow">Workspace</p>{tabs.map(x=><button key={x} className={`nav-item ${tab===x?'active':''}`} onClick={()=>setTab(x)}>{x==='overview'?'Overview':x==='applications'?'Applications':x[0].toUpperCase()+x.slice(1)}</button>)}{tech&&<div className="tech-state"><span className={profile.available_for_jobs?'dot on':'dot'}></span><div><strong>{profile.available_for_jobs?'Available':'Unavailable'}</strong><small>Job status</small></div></div>}</aside>
      <section className="content"><div className="page-head"><div><p className="eyebrow">{isAdmin?'Operations':'Your workspace'}</p><h1>{tab==='overview'?'Good to see you.':tab==='applications'?'Technician applications':tab==='technician'?'Your technician profile':tab==='availability'?'Availability':tab==='payments'?'Payments':'Bookings'}</h1><p className="muted">{isAdmin?'One place for Viso bookings, payments and technician operations.':'Your Viso jobs, availability, earnings and location controls.'}</p></div></div>{error&&<div className="error">{error}</div>}
      {tab==='overview'&&<Overview stats={stats} bookings={bookings} payments={payments} isAdmin={isAdmin} />}
      {tab==='bookings'&&<Bookings bookings={bookings} onStatus={updateBooking} isAdmin={isAdmin} />}
      {tab==='payments'&&<Payments payments={payments} bookings={bookings} />}
      {tab==='applications'&&isAdmin&&<Applications applications={applications} filter={appFilter} setFilter={setAppFilter} onAction={applicationAction}/>} 
      {tab==='technician'&&<TechnicianProfile profile={profile} setProfile={setProfile} services={SERVICES} onToggle={toggleService} onSave={saveProfile} tech={tech} onConnect={connect} locationOn={locationOn} setLocationOn={setLocationOn} locationMsg={locationMsg} onUploadAvatar={uploadAvatar}/>} 
      {tab==='availability'&&<Availability availability={availability} onSave={saveAvailability} onDelete={deleteAvailability} timeOff={timeOff} onAddTimeOff={addTimeOff} onRemoveTimeOff={removeTimeOff} tech={tech}/>} 
      </section></div>
  </main>
}

function Overview({stats,bookings,payments,isAdmin}){return <><div className="stats-grid"><Stat label="Revenue" value={money(stats.revenue)} note="Successful payments"/><Stat label="Today" value={stats.today} note="Bookings scheduled today"/><Stat label="Upcoming" value={stats.upcoming} note="Future appointments"/><Stat label="Pending" value={stats.pending} note="Bookings needing attention"/></div><div className="panel"><div className="panel-head"><div><p className="eyebrow">Schedule</p><h2>{isAdmin?'Latest bookings':'Your upcoming jobs'}</h2></div></div><BookingTable bookings={bookings.slice(0,12)} compact/></div>{isAdmin&&<div className="two-col"><div className="panel"><p className="eyebrow">Payments</p><h2>Recent money in</h2><p className="muted">{payments.filter(p=>['paid','succeeded','completed'].includes(String(p.status||'').toLowerCase())).length} successful payment records.</p></div><div className="panel"><p className="eyebrow">Technician network</p><h2>Applications are review-first.</h2><p className="muted">Applicants stay outside dispatch until approved and onboarded.</p></div></div>}</>}
function Bookings({bookings,onStatus,isAdmin}){return <div className="panel"><div className="panel-head"><div><p className="eyebrow">{isAdmin?'All bookings':'Assigned bookings'}</p><h2>{bookings.length} booking{bookings.length===1?'':'s'}</h2></div></div><BookingTable bookings={bookings} onStatus={onStatus} admin={isAdmin}/></div>}
function BookingTable({bookings,onStatus,admin}){if(!bookings.length)return <div className="empty"><strong>No bookings yet.</strong><span>New Viso bookings will appear here.</span></div>;return <div className="table-wrap"><table><thead><tr><th>Customer</th><th>Service</th><th>When</th><th>Location</th><th>Total</th><th>Status</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><strong>{b.customer_name||'Customer'}</strong><span>{b.customer_email||b.customer_phone||'—'}</span></td><td>{b.service_name||'Service'}<span>{b.assigned_technician_id?'Assigned':'Unassigned'}</span></td><td><strong>{dateLabel(b.appointment_date)}</strong><span>{timeLabel(b.appointment_time)}</span></td><td>{b.location?.address||b.location?.label||'—'}</td><td>{money(b.total)}</td><td>{admin&&onStatus?<select className="mini-select" value={b.status||'pending'} onChange={e=>onStatus(b.id,e.target.value)}><option>pending</option><option>confirmed</option><option>in_progress</option><option>completed</option><option>cancelled</option></select>:<Badge value={b.status}/>}</td></tr>)}</tbody></table></div>}
function Payments({payments,bookings}){return <div className="panel"><div className="panel-head"><div><p className="eyebrow">Stripe</p><h2>Payments & earnings</h2></div></div><div className="table-wrap"><table><thead><tr><th>Booking</th><th>Amount</th><th>Status</th><th>Created</th><th>Stripe</th></tr></thead><tbody>{payments.map(p=>{const b=bookings.find(x=>x.id===p.booking_id);return <tr key={p.id}><td><strong>{b?.customer_name||p.booking_id||'—'}</strong><span>{b?.service_name||'Booking'}</span></td><td>{money(p.amount)}</td><td><Badge value={p.status}/></td><td>{p.created_at?new Date(p.created_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'}</td><td><span className="mono">{p.stripe_payment_intent_id||p.stripe_checkout_session_id||'—'}</span></td></tr>})}</tbody></table></div></div>}
function Applications({applications,filter,setFilter,onAction}){const rows=applications.filter(a=>filter==='all'||a.status===filter);return <div className="panel"><div className="panel-head"><div><p className="eyebrow">Recruiting</p><h2>{rows.length} {filter} application{rows.length===1?'':'s'}</h2></div><select className="mini-select" value={filter} onChange={e=>setFilter(e.target.value)}><option>pending</option><option>approved</option><option>rejected</option><option>all</option></select></div><div className="application-list">{rows.map(a=><article className="application" key={a.id}><div><div className="application-top"><h3>{a.full_name}</h3><Badge value={a.status}/></div><p>{a.email} · {a.phone}</p><p>{a.city}, {a.state} · {a.years_experience||0} years experience</p><div className="chips">{(a.specialties||[]).map(s=><span key={s}>{s}</span>)}</div><p className="muted small">Services: {(a.services||[]).join(', ')||'—'}</p><p className="muted small">Service area: {a.service_radius_miles||'—'} miles · Availability: {a.availability_notes||'—'}</p></div><div className="application-actions">{a.status==='pending'&&<><button className="primary small-btn" onClick={()=>onAction(a.id,'approve_application')}>Approve</button><button className="ghost small-btn" onClick={()=>onAction(a.id,'reject_application')}>Reject</button></>}</div></article>)}</div></div>}
function TechnicianProfile({profile,setProfile,services,onToggle,onSave,tech,onConnect,locationOn,setLocationOn,locationMsg,onUploadAvatar}){return <div className="two-col"><div className="panel"><p className="eyebrow">Profile</p><div className="profile-head">{tech?.avatar_url?<img className="avatar" src={tech.avatar_url} alt="Technician profile"/>:<div className="avatar avatar-placeholder">{(tech?.name||'T').slice(0,1).toUpperCase()}</div>}<div><h2>{tech?.name||'Technician profile'}</h2><label className="ghost upload-label">Change photo<input type="file" accept="image/*" onChange={e=>onUploadAvatar(e.target.files?.[0])}/></label></div></div><div className="form-grid"><label>Name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Phone<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label className="wide">Base address<input value={profile.base_address} onChange={e=>setProfile({...profile,base_address:e.target.value})}/></label><label>Base latitude<input value={profile.base_lat} onChange={e=>setProfile({...profile,base_lat:e.target.value})}/></label><label>Base longitude<input value={profile.base_lng} onChange={e=>setProfile({...profile,base_lng:e.target.value})}/></label></div><p className="field-title">Specialties / services</p><div className="chips selectable">{services.map(([id,label])=><button type="button" key={id} className={profile.services.includes(id)?'selected':''} onClick={()=>onToggle(id)}>{label}</button>)}</div><label className="toggle"><input type="checkbox" checked={profile.available_for_jobs} onChange={e=>setProfile({...profile,available_for_jobs:e.target.checked})}/><span>Available for jobs</span></label><button className="primary" onClick={onSave}>Save technician profile</button></div><div className="panel"><p className="eyebrow">Live location</p><h2>Share your position</h2><p className="muted">Only share location while you are working or available for Viso jobs.</p><label className="toggle"><input type="checkbox" checked={locationOn} onChange={e=>setLocationOn(e.target.checked)}/><span>{locationOn?'Location sharing is on':'Location sharing is off'}</span></label>{locationMsg&&<p className="notice">{locationMsg}</p>}<div className="connect-box"><p className="eyebrow">Stripe Connect</p><h3>{tech?.stripe_connect_account_id?'Connected account created':'Payout account'}</h3><p className="muted">Technicians complete their payout onboarding through Stripe. Viso does not store bank details.</p>{tech?.stripe_connect_account_id?<button className="ghost" onClick={()=>onConnect('onboarding_link')}>Continue Stripe onboarding</button>:<button className="primary" onClick={()=>onConnect('create_account')}>Set up payouts</button>}</div></div></div>}
function Availability({availability,onSave,onDelete,timeOff,onAddTimeOff,onRemoveTimeOff,tech}){const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];const [rows,setRows]=useState(availability);useEffect(()=>setRows(availability),[availability]);function update(i,k,v){setRows(r=>r.map((x,n)=>n===i?{...x,[k]:v}:x))}function add(){setRows(r=>[...r,{id:'new-'+Date.now(),technician_id:tech.id,weekday:1,start_time:'09:00',end_time:'17:00',active:true}])}return <div className="two-col"><div className="panel"><div className="panel-head"><div><p className="eyebrow">Weekly schedule</p><h2>When you can work</h2></div><button className="ghost" onClick={add}>Add interval</button></div><div className="availability-list">{rows.map((r,i)=><div className="availability-row" key={r.id}><select className="mini-select" value={r.weekday} onChange={e=>update(i,'weekday',Number(e.target.value))}>{days.map((d,n)=><option value={n} key={d}>{d}</option>)}</select><input type="time" value={r.start_time} onChange={e=>update(i,'start_time',e.target.value)}/><span>to</span><input type="time" value={r.end_time} onChange={e=>update(i,'end_time',e.target.value)}/><button className="primary tiny" onClick={()=>onSave(r)}>Save</button>{r.id&&!String(r.id).startsWith('new-')&&<button className="ghost tiny" onClick={()=>onDelete(r.id)}>×</button>}</div>)}</div><p className="muted small">You can keep multiple intervals on the same day for split shifts.</p></div><div className="panel"><p className="eyebrow">Time off</p><h2>Block a date</h2><form onSubmit={onAddTimeOff} className="form-stack"><input name="date" type="date" required/><input name="reason" placeholder="Reason (optional)"/><button className="primary">Add time off</button></form><div className="timeoff-list">{timeOff.map(x=><div key={x.id}><span>{dateLabel(x.date)}</span><span>{x.reason||'Unavailable'}</span><button className="ghost tiny" onClick={()=>onRemoveTimeOff(x.id)}>Remove</button></div>)}</div></div></div>}
function Stat({label,value,note}){return <article className="stat"><p>{label}</p><strong>{value}</strong><span>{note}</span></article>}
function Badge({value}){return <span className={`badge ${statusClass(value)}`}>{value||'pending'}</span>}
